#ifndef _LANG_IDS_H_
#define _LANG_IDS_H_

#define STR_GAME_NAME 0
#define STR_MM_PLAY_GAME 1
#define STR_MM_OPTIONS 2
#define STR_MM_ABOUT 3
#define STR_MM_SCORES 4
#define STR_MM_EXIT 5
#define STR_BTN_BACK 6
#define STR_OM_SOUND_EFFECTS 7
#define STR_OM_MUSIC 8
#define STR_OM_ACCELEROMETER 9
#define STR_IG_LEVEL 10
#define STR_IG_SCORE 11
#define STR_IG_LINES 12
#define STR_OM_LANGUAGE 13
#define STR_OM_SWITCH_LANG 14
#define STR_MM_CONTINUE 15
#define STR_IG_GAME_OVER 16
#define STR_ABOUT_TITLE_HEADER 17
#define STR_ABOUT_TITLE_START 18
#define STR_ABOUT_TITLE_1 19
#define STR_ABOUT_TITLE_2 20
#define STR_ABOUT_TITLE_3 21
#define STR_ABOUT_TITLE_4 22
#define STR_ABOUT_TITLE_5 23
#define STR_ABOUT_TITLE_6 24
#define STR_ABOUT_TITLE_7 25
#define STR_ABOUT_TITLE_8 26
#define STR_ABOUT_TITLE_9 27
#define STR_ABOUT_TITLE_10 28
#define STR_ABOUT_TITLE_11 29
#define STR_ABOUT_TITLE_12 30
#define STR_ABOUT_TITLE_13 31
#define STR_ABOUT_TITLE_14 32
#define STR_ABOUT_TITLE_15 33
#define STR_ABOUT_TITLE_16 34
#define STR_ABOUT_TITLE_17 35
#define STR_ABOUT_TITLE_18 36
#define STR_ABOUT_TITLE_19 37
#define STR_ABOUT_TITLE_20 38
#define STR_ABOUT_TITLE_21 39
#define STR_ABOUT_TITLE_END 40
#define STR_IBS_TITLE_1 41
#define STR_IBS_TITLE_2 42
#define STR_IBS_NAME 43
#define STR_IBS_TEST_NAME 44
#define STR_OM_VIBRATION 45
#define STR_IG_NEXT 46
#define STR_MM_SOUND 47
#define STR_SS_TAP_SCREEN 48
#define STR_IBS_RECORD 49
#define STR_GAME_MENU 50
#define STR_IBS_CONFIRM 51
#define STR_OM_LEVEL 52

#endif